### ISSUE TITLE
Getting java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0 in GenericRecyclerViewAdapter on line 91

### ISSUE THREAD

**Issue by abhishektiwarijr** [LeoDroidCoder/generic-adapter#2]
Please add this in GenericRecyclerViewAdapter.java: on line number 91 please
just a size check of list 
@Override
    public void onBindViewHolder(VH holder, int position) {
if (items.size() > 0) {
        T item = items.get(position);
        holder.onBind(item);
    }
}

**Comment by LeoDroidCoder** [comment]
Resolved. 
Check out 1.0.1 version
